---
version: 2

project_name: terraform-provider-dollarbox

before:
  hooks:
    - go mod tidy

builds:
  - id: terraform-provider-dollarbox
    main: .
    binary: "{{ .ProjectName }}_v{{ .Version }}"
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    goos:
      - freebsd
      - darwin
      - linux
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  extra_files:
    - glob: terraform-registry-manifest.json
      name_template: "{{ .ProjectName }}_{{ .Version }}_manifest.json"
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  use_existing_draft: true
  extra_files:
    - glob: terraform-registry-manifest.json
      name_template: "{{ .ProjectName }}_{{ .Version }}_manifest.json"

changelog:
  disable: true
