---
minimum_pre_commit_version: "3.6.0"
default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: gofmt -s -w
        language: system
        types:
          - go

      - id: go-mod-tidy
        name: go mod tidy
        entry: go mod tidy
        language: system
        pass_filenames: false
        files: ^(go\.mod|go\.sum|.*\.go)$

      - id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        pass_filenames: false
        stages:
          - pre-push

      - id: go-test
        name: go test
        entry: go test ./...
        language: system
        pass_filenames: false
        stages:
          - pre-push

      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run
        language: system
        pass_filenames: false
        stages:
          - pre-push
